blank_issues_enabled: false
contact_links:
  - name: EasyDutch Issues
    url: https://github.com/EasyDutch-uBlockOrigin/EasyDutch/issues
    about: Report issues concerning EasyDutch in the EasyDutch issue tracker.
